// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtYW4kiKzOqHFRPKAdWErUq0vaViVARYk',
    appId: '1:1085226124876:web:5eda8c0b889e706c0916e9',
    messagingSenderId: '1085226124876',
    projectId: 'islamicappchat',
    authDomain: 'islamicappchat.firebaseapp.com',
    storageBucket: 'islamicappchat.firebasestorage.app',
    measurementId: 'G-YB6316X944',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDks7K3f6BpD3rIPU-v-0Jc5VI-EsBvvoA',
    appId: '1:1085226124876:android:240887b87b40af9f0916e9',
    messagingSenderId: '1085226124876',
    projectId: 'islamicappchat',
    storageBucket: 'islamicappchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbgtQCyALiVhv_yz2E_rBCYEQI0gnP-28',
    appId: '1:1085226124876:ios:7f4ccdf547d688b50916e9',
    messagingSenderId: '1085226124876',
    projectId: 'islamicappchat',
    storageBucket: 'islamicappchat.firebasestorage.app',
    iosBundleId: 'com.example.islamicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbgtQCyALiVhv_yz2E_rBCYEQI0gnP-28',
    appId: '1:1085226124876:ios:7f4ccdf547d688b50916e9',
    messagingSenderId: '1085226124876',
    projectId: 'islamicappchat',
    storageBucket: 'islamicappchat.firebasestorage.app',
    iosBundleId: 'com.example.islamicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtYW4kiKzOqHFRPKAdWErUq0vaViVARYk',
    appId: '1:1085226124876:web:f24e7084424323340916e9',
    messagingSenderId: '1085226124876',
    projectId: 'islamicappchat',
    authDomain: 'islamicappchat.firebaseapp.com',
    storageBucket: 'islamicappchat.firebasestorage.app',
    measurementId: 'G-Z80C6MGVJQ',
  );
}
